# Generated by Django 3.0.5 on 2020-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ham', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ham',
            name='statu',
        ),
        migrations.AddField(
            model_name='ham',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
