# Generated by Django 3.0.5 on 2020-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ham', '0004_ham_recent_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ham',
            name='recent_result',
            field=models.BooleanField(default=True),
        ),
    ]
